# SPDX-License-Identifier: Apache-2.0

import re
import sys
from os.path import abspath, dirname, join

import sphinx_material

sys.path.insert(0, abspath(".."))

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.coverage",
    "sphinx.ext.intersphinx",
    "sphinx-mathjax-offline",
    "sphinx.ext.napoleon",  # before sphinx_autodoc_typehints
    "sphinx_autodoc_typehints",
]

# List of modules to be mocked up.
autodoc_mock_imports = [
    "robot_descriptions",
    "trimesh",
    "viser",
    "yourdfpy",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# The suffix(es) of source filenames.
source_suffix = {".rst": "restructuredtext"}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "pinker"
copyright = "2026 CNRS"
author = "Stéphane Caron"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# The short X.Y version.
version = None

# The full version, including alpha/beta/rc tags.
release = None

# Read version info directly from the module's __init__.py
init_path = join(dirname(dirname(str(abspath(__file__)))), "pinker")
with open(f"{init_path}/__init__.py", "r") as fh:
    for line in fh:
        match = re.match('__version__ = "((\\d.\\d).\\d)[a-z0-9\\-]*".*', line)
        if match is not None:
            release = match.group(1)
            version = match.group(2)
            break

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also affects `html_static_path` and `html_extra_path`.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# "Show Source" link in the right-hand side bar
html_show_sourcelink = False

html_sidebars = {
    "**": [
        "logo-text.html",
        "globaltoc.html",
        "localtoc.html",
        "searchbox.html",
    ]
}

# The theme to use for HTML and HTML Help pages.
html_theme = "sphinx_material"

# Set link name generated in the top bar.
html_title = "pinker"

# Theme options are theme-specific. The "pink" primary and accent colors are
# re-shaded to Pinker's own palette in css/custom.css.
html_theme_options = {
    "color_primary": "pink",
    "color_accent": "pink",
    "globaltoc_depth": 1,
    "localtoc_label_text": "Contents",
    "nav_links": [
        {"href": "installation", "internal": True, "title": "Installation"},
        {"href": "tasks", "internal": True, "title": "Tasks"},
        {"href": "limits", "internal": True, "title": "Limits"},
        {"href": "barriers", "internal": True, "title": "Barriers"},
        {
            "href": "inverse-kinematics",
            "internal": True,
            "title": "Inverse kinematics",
        },
    ],
    "repo_url": "https://github.com/pink-kinematics/pinker/",
    "repo_name": "pinker",
    "theme_color": "#d4619c",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["css"]

# These paths are either relative to html_static_path or fully qualified paths
# (eg. https://...)
html_css_files = ["custom.css"]

# Fixes the warning "cannot cache unpickable configuration value"
html_context = sphinx_material.get_html_context()

intersphinx_mapping = {
    "numpy": ("https://numpy.org/doc/stable", None),
    "python": ("https://docs.python.org/3", None),
    "qpsolvers": ("https://qpsolvers.github.io/qpsolvers/", None),
}

# Render array-like annotations as the alias rather than as the union NumPy
# expands it to, which has no documented target to link to
autodoc_type_aliases = {
    "ArrayLike": "numpy.typing.ArrayLike",
}

suppress_warnings = [
    # The theme's html_context holds a function, which Sphinx cannot pickle
    "config.cache",
    # The Viser visualizer imports viser lazily, so that the rest of the
    # library runs without it. Documenting it does not require it either.
    "sphinx_autodoc_typehints.guarded_import",
]

# Treat warnings as errors, in particular when a reference target (such as a
# :func:`something`) is not found.
nitpicky = True

nitpick_ignore = [
    ("py:class", "pinker.kinematics.model._SE3View"),  # private view type
    ("py:class", "numpy.float64"),
    ("py:class", "viser.ViserServer"),
    ("py:data", "typing.Optional"),
    ("py:data", "typing.Tuple"),
    ("py:data", "typing.Union"),
]
